const SET_MAP = "SET_MAP";

const ADD_FEATURE = "ADD_FEATURE";
const DELETE_FEATURE = "DELETE_FEATURE";
const UPDATE_FEATURE = "UPDATE_FEATURE";

const CHANGE_MARKER = "CHANGE_MARKER";
const CHANGE_MARKER_COLOR = "CHANGE_MARKER_COLOR";
const CHANGE_LAYER = "CHANGE_LAYER";

export {
  SET_MAP,
  ADD_FEATURE,
  DELETE_FEATURE,
  UPDATE_FEATURE,
  CHANGE_MARKER,
  CHANGE_MARKER_COLOR,
  CHANGE_LAYER,
};
