const LOGIN_START = "LOGIN_START";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_ERROR = "LOGIN_ERROR";
const LOGOUT = "LOGOUT";
const SET_USER = "SET_USER";

export { LOGIN_START, LOGIN_SUCCESS, LOGIN_ERROR, LOGOUT, SET_USER };
